import { CommittingState, InputState } from '../input_method/InputState';
import Layout from './Layout';

export default class DzongkhaLayout implements Layout {
  handle(
    key: string,
    state: InputState,
    stateCallback: (newState: InputState) => void,
    errorCallback: () => void,
  ): boolean {
    const code = this.keymap.get(key);
    if (code) {
      stateCallback(new CommittingState(code));
      return true;
    }
    return false;
  }
  readonly layoutId = 'dzongkha';
  readonly layoutName = 'Dzongkha';

  readonly keymap = new Map<string, string>([
    ['_', 'ཿ'],
    ['-', '༔'],
    [',', 'ས'],
    [';', 'ཚ'],
    [':', 'ྪ'],
    ['!', '༄'],
    ['?', 'ྸ'],
    ['.', 'ཧ'],
    ['"', 'ྫ'],
    ['(', '༼'],
    [')', '༽'],
    ['[', 'ཇ'],
    [']', 'ཉ'],
    ['{', 'ྗ'],
    ['}', 'ྙ'],
    ['@', '༅'],
    ['*', '༴'],
    ['/', 'ཨ'],
    ['\\', 'ཝ'],
    ['&', '༸'],
    ['#', '༆'],
    ['%', '༎'],
    ['`', '༉'],
    ['^', '༈'],
    ['+', '༑'],
    ['<', 'ྶ'],
    ['=', '།'],
    ['>', 'ྸ'],
    ['|', 'ྭ'],
    ['~', '༊'],
    ['$', ''],
    ['0', '༠'],
    ['1', '༡'],
    ['2', '༢'],
    ['3', '༣'],
    ['4', '༤'],
    ['5', '༥'],
    ['6', '༦'],
    ['7', '༧'],
    ['8', '༨'],
    ['9', '༩'],
    ['A', ' ྟ'],
    ['a', 'ཏ'],
    ['B', ' ྲ'],
    ['b', 'ར'],
    ['C', ' ཱ'],
    ['c', 'འ'],
    ['D', ' ྡ'],
    ['d', 'ད'],
    ['E', ' ྒ'],
    ['e', 'ག'],
    ['F', ' ྣ'],
    ['f', 'ན'],
    ['G', ' ྤ'],
    ['g', 'པ'],
    ['H', ' ྥ'],
    ['h', 'ཕ'],
    ['I', ' ཽ'],
    ['i', 'ོ'],
    ['J', ' ྦ'],
    ['j', 'བ'],
    ['K', ' ྨ'],
    ['k', 'མ'],
    ['L', ' ྩ'],
    ['l', 'ཙ'],
    ['M', ' ྴ'],
    ['m', 'ཤ'],
    ['N', ' ླ'],
    ['n', 'ལ'],
    ['O', ' ྕ'],
    ['o', 'ཅ'],
    ['P', ' ྖ'],
    ['p', 'ཆ'],
    ['Q', ' ྐ'],
    ['q', 'ཀ'],
    ['R', ' ྔ'],
    ['r', 'ང'],
    ['S', ' ྠ'],
    ['s', 'ཐ'],
    ['T', ' ྀ'],
    ['t', 'ི'],
    ['U', ' ཻ'],
    ['u', 'ེ'],
    ['V', ' ྱ'],
    ['v', 'ཡ'],
    ['W', ' ྑ'],
    ['w', 'ཁ'],
    ['X', ' ྯ'],
    ['x', 'ཟ'],
    ['Y', ' ྄'],
    ['y', 'ུ'],
    ['Z', ' ྮ'],
    ['z', 'ཞ'],
    ["'", 'ཛ'],
  ]);
}
